"""empty message

Revision ID: 3cd6454f570c
Revises: bf5f579eba66
Create Date: 2020-07-12 19:56:11.447872

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3cd6454f570c'
down_revision = 'bf5f579eba66'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'link', ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'link', type_='unique')
    # ### end Alembic commands ###
